pool: 
  vmImage: 'ubuntu-latest'

trigger:
  - master

variables:
  system.debug: true

steps:
  - task: UseNode@1
    inputs:
      versionSpec: '16.x'  # You can specify the version you need here
    displayName: 'Install Node.js'

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/Templates'
    inputs:
      SourceFolder: 'deployment'
      Contents: '*.json'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/Templates'

  - task: Npm@1
    displayName: 'Install npm packages'
    inputs:
      command: 'install'

  - task: ArchiveFiles@2
    displayName: 'Archive $(Build.SourcesDirectory)'
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      publishLocation: 'Container'
